// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using monitKars.Data;

#nullable disable

namespace monitKars.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("monitKars.Entities.Car", b =>
                {
                    b.Property<int>("CarID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CarID"));

                    b.Property<string>("CarColor")
                        .HasColumnType("text");

                    b.Property<string>("CarEngine")
                        .HasColumnType("text");

                    b.Property<string>("CarInsurance")
                        .HasColumnType("text");

                    b.Property<string>("CarMaintenanceStatus")
                        .HasColumnType("text");

                    b.Property<string>("CarManufacturer")
                        .HasColumnType("text");

                    b.Property<string>("CarMilage")
                        .HasColumnType("text");

                    b.Property<string>("CarModel")
                        .HasColumnType("text");

                    b.Property<string>("CarName")
                        .HasColumnType("text");

                    b.Property<string>("CarOil")
                        .HasColumnType("text");

                    b.Property<string>("CarOrganisation")
                        .HasColumnType("text");

                    b.Property<string>("CarOwnerID")
                        .HasColumnType("text");

                    b.Property<string>("CarPeriodicRevision")
                        .HasColumnType("text");

                    b.Property<string>("CarPlateNumber")
                        .HasColumnType("text");

                    b.Property<string[]>("CarTireSizes")
                        .HasColumnType("text[]");

                    b.Property<string>("CarType")
                        .HasColumnType("text");

                    b.Property<string>("CarVignette")
                        .HasColumnType("text");

                    b.Property<string>("CarVinNumber")
                        .HasColumnType("text");

                    b.Property<int?>("CarYear")
                        .HasColumnType("integer");

                    b.HasKey("CarID");

                    b.ToTable("Car", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
