### STAGE 1: Build ###
FROM node:19.1-alpine AS build

RUN apk update && apk upgrade && apk add --no-cache bash git openssh ca-certificates && rm -rf /var/cache/apk/*

WORKDIR /usr/src/app
COPY monitKars .

RUN npm cache clean --force
# Install all the dependencies
#RUN npm install
RUN npm install --legacy-peer-deps && npm install -g @angular/cli@15.0.0 --legacy-peer-deps

RUN npm audit fix --legacy-peer-deps
# Generate the build of the application

RUN ng build --output-hashing=all --optimization


### STAGE 2: Run ###
FROM nginx:1.23.2-alpine
COPY --from=build /usr/src/app/dist/monit-kars/ /usr/share/nginx/html
COPY ./nginx_angular.conf /etc/nginx/conf.d/default.conf
CMD ["/bin/sh",  "-c",  "exec nginx -g 'daemon off;'"]

# Expose port 80
EXPOSE 80