
FROM node:20.10-alpine AS build

RUN apk update && apk upgrade && apk add --no-cache bash git openssh ca-certificates && rm -rf /var/cache/apk/*

WORKDIR /usr/src/app
COPY monitKars .

RUN npm install && npm install -g @angular/cli@17.0.3

RUN ng build

FROM nginx:1.23.2-alpine
COPY --from=build /usr/src/app/dist/monit-kars/ /usr/share/nginx/html
COPY ./nginx_angular.conf /etc/nginx/conf.d/default.conf
CMD ["/bin/sh",  "-c",  "envsubst < /usr/share/nginx/html/assets/env.template.js > /usr/share/nginx/html/assets/env.js && exec nginx -g 'daemon off;'"]

EXPOSE 80