version: '3.8'
services:
  frontend:
    container_name: angular_container
    restart: unless-stopped
    build:
      context: ./frontend
      dockerfile: Dockerfile_frontend
    ports:
      - '4200:80'
    networks:
      - default

  database:
    container_name: postgres_container
    restart: unless-stopped
    image: postgres:15.1-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: monitKars
    ports:
      - '5432:5432'
    volumes: 
      - database:/var/lib/postgresql/data
    networks:
      - default

  backend:
    container_name: dotnet_container
    restart: unless-stopped
    build:
      context: ./backend
      dockerfile: Dockerfile_backend
    environment:
    - ConnectionStrings__WebApiDatabase=Host=database;Port=5432;Database=monitKars;Username=postgres;Password=postgres
    ports:
      - '7148:80'
    networks:
      - default
  
volumes:
  database:
    driver: local

networks:
  default:
    driver: bridge