version: '3.8'
services:
  # frontend:
  #   container_name: angular_container
  #   restart: unless-stopped
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile_frontend
  #   ports:
  #     - '4200:80'
  #   networks:
  #     - default

  database:
    container_name: postgres_container
    restart: unless-stopped
    image: postgres:15.1-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: monitKars
    ports:
      - '5432:5432'
    volumes: 
      - database:/var/lib/postgresql/data
    networks:
      - default
    
  database_admin:
    container_name: pgadmin
    restart: unless-stopped
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@postgres.com
      PGADMIN_DEFAULT_PASSWORD: postgres
    ports:
      - '3100:80'
    volumes:
       - pgadmin:/root/.pgadmin
    networks:
      - default

  auth_provider:
    container_name: keycloak-auth
    restart: unless-stopped
    image: quay.io/keycloak/keycloak:21.0.1
    ports:
      - '4335:8080'
    volumes:
      - keycloak:/opt/keycloak/data/
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: database
      KC_DB_URL_DATABASE: postgres
      KC_DB_SCHEMA: public
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: postgres
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: P@ssw0rd
      # Uncomment the line below if you want to specify JDBC parameters. The parameter below is just an example, and it shouldn't be used in production without knowledge. It is highly recommended that you read the PostgreSQL JDBC driver documentation in order to use it.
      #JDBC_PARAMS: "ssl=true"
    command: ['start-dev']
    networks:
      - default

  # backend:
  #   container_name: dotnet_container
  #   restart: unless-stopped
  #   build:
  #     context: ./backend
  #     dockerfile: Dockerfile_backend
  #   environment:
  #   - ConnectionStrings__WebApiDatabase=Host=database;Port=5432;Database=monitKars;Username=postgres;Password=postgres
  #   ports:
  #     - '7148:80'
  #   networks:
  #     - default
  
volumes:
  database:
    driver: local
  pgadmin:
    driver: local
  keycloak:
    driver: local

networks:
  default:
    driver: bridge