FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /app
COPY monitKars .
WORKDIR /app/
RUN dotnet restore monitKars.sln
RUN dotnet publish monitKars.sln -c Release -o out

FROM mcr.microsoft.com/dotnet/aspnet:6.0
WORKDIR /app
COPY --from=build /app/out .

ENTRYPOINT ["dotnet", "monitKars.dll"]