version: '3'

services:

  db:
    image: mysql:latest
    container_name: db
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_PASSWORD: admin
    networks:
      - app-network
    volumes:
      - dbdata:/var/lib/mysql/

# this is if i want to build the image again locally
  # laravelLocal:
  #   container_name: php-node-container
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8000:80"
  #   networks:
  #     - app-network

# this is if i want to pull the image from dockerhub
  laravelDockerHub:
    image: reddd1/licenta-webapp-laravel:v0.1 # remember to change the version if u create a new version
    container_name: php-node-container
    ports:
      - "8000:80"
    networks:
      - app-network


networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
    driver: local